FirstMVCApp.UI/Models/Products/ProductCreateModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FirstMVCApp.UI.Models.Products
{
    public class ProductCreateModel
    {
        [Display(Name = "Наименование")]
        [Required(ErrorMessage = "Наименование должно быть заполненным")]
        public string Name { get; set; }

        [Display(Name = "Категория")]
        [Required(ErrorMessage = "Категория должно быть указана")]
        public int CategoryId { get; set; }

        [Display(Name = "Брэнд")]
        public int? BrandId { get; set; }

        [Display(Name = "Цена")]
        [Required(ErrorMessage = "Цена должно быть указана")]
        [Range(0, Double.PositiveInfinity, ErrorMessage = "Цена не может быть отрицательной")]
        public decimal Price { get; set; }
        public SelectList CategoriesSelect { get; set; }
        public SelectList BrandsSelect { get; set; }
    }
}

FirstMVCApp.UI/Models/Products/ProductEditModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FirstMVCApp.UI.Models.Products
{
    public class ProductEditModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public string BrandId { get; set; }
        public decimal Price { get; set; }
        public SelectList CategoriesSelect { get; set; }
        public SelectList BrandsSelect { get; set; }
    }
}

FirstMVCApp.UI/Models/Products/ProductFilterModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FirstMVCApp.UI.Models.Products
{
    public class ProductFilterModel
    {
        public string Name { get; set; }
        public int? CategoryId { get; set; }
        public int? BrandId { get; set; }
        public decimal? PriceFrom { get; set; }
        public decimal? PriceTo { get; set; }
        public List<ProductModel> Products { get; set; }
        public SelectList CategoriesSelect { get; set; }
        public SelectList BrandsSelect { get; set; }
    }
}

FirstMVCApp.UI/Models/Products/ProductModel.cs
namespace FirstMVCApp.UI.Models.Products
{
    public class ProductModel
    {
        public static string NoBrand = "NoName";

        public int Id { get; set; }
        public string Name { get; set; }
        public string CategoryName { get; set; }
        public string BrandName { get; set; }
        public decimal Price { get; set; }
    }
}

FirstMVCApp.UI/Controllers/BucketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using FirstMVCApp.DAL.Entities;
using FirstMVCApp.UI.Services.Bucket;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FirstMVCApp.UI.Controllers
{
    public class BucketController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IBucketService _bucketService;

        public BucketController(UserManager<User> userManager, IBucketService bucketService)
        {
            _userManager = userManager;
            _bucketService = bucketService;
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Add(int? productId)
        {
            if (!productId.HasValue)
            {
                ViewBag.BadRequestMessage = "Product Id can not be NULL";
                return View("BadRequest");
            }

            try
            {
                User currentUser = await _userManager.GetUserAsync(User);
                await _bucketService.AddToBucketAsync(productId.Value, currentUser);
                return RedirectToAction("Index", "Product");
            }
            catch (Exception e)
            {
                return StatusCode(500, e);
            }
        }
    }
}

FirstMVCApp.UI/Controllers/ProductController.cs
using System;
using FirstMVCApp.UI.Models.Products;
using FirstMVCApp.UI.Services.Products.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace FirstMVCApp.UI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            if(productService == null)
                throw new ArgumentNullException(nameof(productService));

            _productService = productService;
        }

        [Route("Search/{name?}/{categoryId?}/{brandId?}/{priceFrom?}/{priceTo?}")]
        public IActionResult Index(ProductFilterModel model)
        {
            try
            {
                var products = _productService.SearchProducts(model);

                model.Products = products;
                model.CategoriesSelect = _productService.GetCategoriesSelect();
                model.BrandsSelect = _productService.GetBrandsSelect();

                return View(model);
            }
            catch (ArgumentOutOfRangeException ex)
            {
                ViewBag.BadRequestMessage = ex.Message;
                return View("BadRequest");
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }

        public IActionResult Create()
        {
            var model = _productService.GetProductCreateModel();

            return View(model);
        }

        [HttpPost]
        public IActionResult Create(ProductCreateModel model)
        {
            try
            {
                _productService.CreateProduct(model);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }

        [Route("Edit/{id?}")]
        public IActionResult Edit(int? id)
        {
            if (!id.HasValue)
            {
                ViewBag.BadRequestMessage = "Product id cannot be NULL";
                return View("BadRequest");
            }

            var productEditModel = _productService.GetProductById(id.Value);

            return View(productEditModel);
        }

        [HttpPost]
        public IActionResult EditProduct(ProductEditModel model)
        {
            try
            {
                _productService.EditProduct(model);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }

        // Category Brand Name Price

        [Route("ololo")]
        public string GetString()
        {
            return "OLOLO";
        }
    }
}

FirstMVCApp.UI/Views/Product/Create.cshtml
@model FirstMVCApp.UI.Models.Products.ProductCreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="Model.CategoriesSelect"></select>
            </div>
            <div class="form-group">
                <label asp-for="BrandId" class="control-label"></label>
                <select asp-for="BrandId" class="form-control" asp-items="Model.BrandsSelect">
                    <option></option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FirstMVCApp.UI/Views/Product/Edit.cshtml
@model FirstMVCApp.UI.Models.Products.ProductEditModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>ProductEditModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditProduct" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" type="hidden" value="@Model.Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="Model.CategoriesSelect"></select>
            </div>
            <div class="form-group">
                <label asp-for="BrandId" class="control-label"></label>
                <select asp-for="BrandId" class="form-control" asp-items="Model.BrandsSelect">
                    <option></option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FirstMVCApp.UI/Views/Product/Index.cshtml
@model FirstMVCApp.UI.Models.Products.ProductFilterModel
@{
    ViewData["Title"] = "Products";
}

<h1>Products</h1>
<a asp-controller="Product" asp-action="Create">Create</a>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Index" method="get">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" value="@Model.Name"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriceFrom" class="control-label"></label>
                <input asp-for="PriceFrom" class="form-control" value="@Model.PriceFrom"/>
                <span asp-validation-for="PriceFrom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriceTo" class="control-label"></label>
                <input asp-for="PriceTo" class="form-control" value="@Model.PriceTo"/>
                <span asp-validation-for="PriceTo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="Model.CategoriesSelect">
                    <option></option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="BrandId" class="control-label"></label>
                <select asp-for="BrandId" class="form-control" asp-items="Model.BrandsSelect">
                    <option></option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<table class="table">
    <thead>
    <tr>
        <th>
            Наименование
        </th>
        <th>
            Категория
        </th>
        <th>
            Брэнд
        </th>
        <th>
            Цена
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Products) {
        <tr>
            <td>
                <a asp-action="Edit" asp-controller="Product" asp-route-id="@item.Id">
                    @item.Name
                </a>
            </td>
            <td>
                @item.CategoryName
            </td>
            <td>
                @item.BrandName
            </td>
            <td>
                @item.Price
            </td>
            <td>
                <form asp-action="Add" asp-controller="Bucket" method="post">
                    <input type="hidden" name="productId" value="@item.Id"/>
                    <input type="submit" value="Добавить в корзину"/>
                </form>
            </td>
        </tr>
    }
    </tbody>
</table>